# Site settings
title: Hackmops
feed_title: Hackmops
email: chris@hackmops.com
xmpp: chrifpa@jabber.ccc.de
description: "My name's Chris, I'm an iOS Developer."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hackmops.com" # the base hostname & protocol for your site
assets: "/assets/"
twitter_username: chrifpa
github_username:  chrifpa
adn_username:     chrifpa
link_char: "&#160;↦"
icon_char: "☆&#160;"
excerpt_separator: "<!-- break -->"

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "page:num"

exclude: ["README.md", "TODO.md", "Gemfile", "s3_website.yml", ".travis.yml"]

collections:
    projects:
        output: true
        permalink: /projects/:name/


defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
